# ref1. https://cloud.google.com/build/docs/building/build-containerize-java?hl=ko
# ref2. https://cloud.google.com/build/docs/optimize-builds/building-leaner-containers?hl=ko

steps:
  - name: gradle:8.6.0-jdk17
    env: ['GRADLE_USER_HOME=cache']
    entrypoint: './gradlew'
    args: ['-x', 'test', 'build', '-Dquarkus.profile=dev', '-PisLocal=false']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'us-central1-docker.pkg.dev/gen8id/cloud-run-source-deploy/bitflow-rnd-sbas-backend-api:latest',
           '-t', 'us-central1-docker.pkg.dev/gen8id/cloud-run-source-deploy/bitflow-rnd-sbas-backend-api:$COMMIT_SHA',
           '-f', 'Dockerfile',
           '.'
    ]
    
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/gen8id/cloud-run-source-deploy/bitflow-rnd-sbas-backend-api:latest'
  - 'us-central1-docker.pkg.dev/gen8id/cloud-run-source-deploy/bitflow-rnd-sbas-backend-api:$COMMIT_SHA'